import { z } from "zod";

const envSchema = z.object({
  DATABASE_URL: z.string().min(1).optional(),
  APP_DATABASE_URL: z.string().min(1).optional(),
  GEN_MUMIN_DATABASE_URL: z.string().min(1).optional(),
  APP_URL: z.string().url(),
  APP_ENV: z.enum(["development", "staging", "production"]).default("development"),
  AUTH_SESSION_SECRET: z.string().min(16),
  AUTH_COOKIE_NAME: z.string().min(1).default("gen_mumins_session"),
  RESEND_API_KEY: z.string().min(1).optional(),
  EMAIL_FROM: z.string().min(1).optional(),
  ADMIN_NOTIFICATION_EMAIL: z.string().email().optional(),
  EXTERNAL_ADMIN_FEED_SECRET: z.string().min(16).optional(),
  STRIPE_PUBLISHABLE_KEY: z.string().min(1).optional(),
  STRIPE_SECRET_KEY: z.string().min(1).optional(),
  STRIPE_WEBHOOK_SECRET: z.string().min(1).optional(),
  PAYPAL_CLIENT_ID: z.string().min(1).optional(),
  PAYPAL_CLIENT_SECRET: z.string().min(1).optional(),
  PAYPAL_ENVIRONMENT: z.enum(["SANDBOX", "LIVE"]).optional(),
  PAYPAL_PRODUCT_ID: z.string().min(1).optional(),
  PAYPAL_PLAN_GBP_BUNDLE: z.string().min(1).optional(),
  PAYPAL_PLAN_GBP_PAIR: z.string().min(1).optional(),
  PAYPAL_PLAN_GBP_SEERAH: z.string().min(1).optional(),
  PAYPAL_PLAN_GBP_LIFE_LESSONS: z.string().min(1).optional(),
  PAYPAL_PLAN_USD_BUNDLE: z.string().min(1).optional(),
  PAYPAL_PLAN_AED_BUNDLE: z.string().min(1).optional(),
  PAYPAL_PLAN_SAR_BUNDLE: z.string().min(1).optional(),
  PAYPAL_PLAN_PKR_BUNDLE: z.string().min(1).optional(),
  PAYPAL_PLAN_PKR_PAIR: z.string().min(1).optional(),
  PAYPAL_PLAN_PKR_SEERAH: z.string().min(1).optional(),
  PAYPAL_PLAN_PKR_LIFE_LESSONS: z.string().min(1).optional(),
  MANUAL_PAYMENT_SUPPORT_WHATSAPP: z.string().min(1).optional(),
  BANK_TRANSFER_BANK_NAME: z.string().min(1).optional(),
  BANK_TRANSFER_ACCOUNT_NAME: z.string().min(1).optional(),
  BANK_TRANSFER_ACCOUNT_NUMBER: z.string().min(1).optional(),
  BANK_TRANSFER_IBAN: z.string().min(1).optional(),
  JAZZCASH_ACCOUNT_NAME: z.string().min(1).optional(),
  JAZZCASH_MOBILE_NUMBER: z.string().min(1).optional(),
});

export const env = envSchema.safeParse({
  DATABASE_URL: process.env.DATABASE_URL,
  APP_DATABASE_URL: process.env.APP_DATABASE_URL,
  GEN_MUMIN_DATABASE_URL: process.env.GEN_MUMIN_DATABASE_URL,
  APP_URL: process.env.APP_URL,
  APP_ENV: process.env.APP_ENV,
  AUTH_SESSION_SECRET: process.env.AUTH_SESSION_SECRET,
  AUTH_COOKIE_NAME: process.env.AUTH_COOKIE_NAME,
  RESEND_API_KEY: process.env.RESEND_API_KEY,
  EMAIL_FROM: process.env.EMAIL_FROM,
  ADMIN_NOTIFICATION_EMAIL: process.env.ADMIN_NOTIFICATION_EMAIL,
  EXTERNAL_ADMIN_FEED_SECRET: process.env.EXTERNAL_ADMIN_FEED_SECRET,
  STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
  PAYPAL_CLIENT_ID: process.env.PAYPAL_CLIENT_ID,
  PAYPAL_CLIENT_SECRET: process.env.PAYPAL_CLIENT_SECRET,
  PAYPAL_ENVIRONMENT: process.env.PAYPAL_ENVIRONMENT,
  PAYPAL_PRODUCT_ID: process.env.PAYPAL_PRODUCT_ID,
  PAYPAL_PLAN_GBP_BUNDLE: process.env.PAYPAL_PLAN_GBP_BUNDLE,
  PAYPAL_PLAN_GBP_PAIR: process.env.PAYPAL_PLAN_GBP_PAIR,
  PAYPAL_PLAN_GBP_SEERAH: process.env.PAYPAL_PLAN_GBP_SEERAH,
  PAYPAL_PLAN_GBP_LIFE_LESSONS: process.env.PAYPAL_PLAN_GBP_LIFE_LESSONS,
  PAYPAL_PLAN_USD_BUNDLE: process.env.PAYPAL_PLAN_USD_BUNDLE,
  PAYPAL_PLAN_AED_BUNDLE: process.env.PAYPAL_PLAN_AED_BUNDLE,
  PAYPAL_PLAN_SAR_BUNDLE: process.env.PAYPAL_PLAN_SAR_BUNDLE,
  PAYPAL_PLAN_PKR_BUNDLE: process.env.PAYPAL_PLAN_PKR_BUNDLE,
  PAYPAL_PLAN_PKR_PAIR: process.env.PAYPAL_PLAN_PKR_PAIR,
  PAYPAL_PLAN_PKR_SEERAH: process.env.PAYPAL_PLAN_PKR_SEERAH,
  PAYPAL_PLAN_PKR_LIFE_LESSONS: process.env.PAYPAL_PLAN_PKR_LIFE_LESSONS,
  MANUAL_PAYMENT_SUPPORT_WHATSAPP: process.env.MANUAL_PAYMENT_SUPPORT_WHATSAPP,
  BANK_TRANSFER_BANK_NAME: process.env.BANK_TRANSFER_BANK_NAME,
  BANK_TRANSFER_ACCOUNT_NAME: process.env.BANK_TRANSFER_ACCOUNT_NAME,
  BANK_TRANSFER_ACCOUNT_NUMBER: process.env.BANK_TRANSFER_ACCOUNT_NUMBER,
  BANK_TRANSFER_IBAN: process.env.BANK_TRANSFER_IBAN,
  JAZZCASH_ACCOUNT_NAME: process.env.JAZZCASH_ACCOUNT_NAME,
  JAZZCASH_MOBILE_NUMBER: process.env.JAZZCASH_MOBILE_NUMBER,
});
