import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { ActionToast } from "@/components/dashboard/ActionToast";
import { FardhTrackerBoard } from "@/components/community/FardhTrackerBoard";
import { FamilyDashboardFrame } from "@/components/dashboard/family/FamilyDashboardFrame";
import { getCurrentSession, getDashboardHome } from "@/lib/auth/session";
import { getStudentDashboardData } from "@/lib/dashboard/family";
import { getStudentNavItems } from "@/lib/dashboard/family-nav";
import { ensureFardhReminder,getFardhWeek,saveFardhDay,type FardhPrayerKey } from "@/lib/community/fardh-tracker";
type Props={searchParams?:Promise<{week?:string;saved?:string;points?:string}>};
export default async function StudentFardhTrackerPage({searchParams}:Props){const session=await getCurrentSession();if(!session)redirect('/auth/login');if(session.user.role!=='STUDENT')redirect(getDashboardHome(session.user.role));const dashboard=await getStudentDashboardData(session.user.id);if(!dashboard)redirect('/auth/login');const params=searchParams?await searchParams:{};const child=dashboard.child;const timezone=child.profile.timezone||'Europe/London';await ensureFardhReminder(session.user.id,'/student/fardh-tracker',timezone);const week=await getFardhWeek(child.id,params.week,timezone);async function save(formData:FormData){'use server';const current=await getCurrentSession();if(!current||current.user.role!=='STUDENT')redirect('/auth/login');const currentDashboard=await getStudentDashboardData(current.user.id);if(!currentDashboard)redirect('/auth/login');const tz=currentDashboard.child.profile.timezone||'Europe/London';const result=await saveFardhDay({studentId:currentDashboard.child.id,dayKey:String(formData.get('dayKey')||''),timezone:tz,prayers:formData.getAll('prayer').map(String) as FardhPrayerKey[]});revalidatePath('/student/fardh-tracker');revalidatePath('/parent/fardh-tracker');redirect(`/student/fardh-tracker?saved=1&points=${result.points}`)}return <FamilyDashboardFrame roleLabel="Student Dashboard" title="My Fardh Prayer Tracker" subtitle="Build a steady salah habit, one honest prayer at a time." navItems={getStudentNavItems()} pendingReason={dashboard.pendingReason}><ActionToast message={params.saved?`Prayer tracker saved. ${params.points||0} new points awarded—never duplicated.`:undefined}/><FardhTrackerBoard {...week} action={save} locked={child.accessLocked}/></FamilyDashboardFrame>}