import Link from "next/link";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { ActionToast } from "@/components/dashboard/ActionToast";
import { getCurrentSession } from "@/lib/auth/session";
import { HOUSE_UNLOCKS } from "@/lib/community/recognition";
import { db } from "@/lib/db";
type Props={searchParams?:Promise<{notice?:string;tone?:string}>};
const go=(notice:string,tone:"success"|"error"="success")=>"/admin/rewards?"+new URLSearchParams({notice,tone});
const name=(s:{displayName:string|null;user:{firstName:string;lastName:string|null}})=>s.displayName||(s.user.firstName+" "+(s.user.lastName||"")).trim();

export default async function Page({searchParams}:Props){
 const session=await getCurrentSession();if(!session||session.user.role!=="ADMIN")redirect("/admin");const params=searchParams?await searchParams:{};
 const totals=await db.housePointLedger.groupBy({by:["houseId"],_sum:{points:true}});
 for(const row of totals)for(const item of HOUSE_UNLOCKS.filter(x=>(row._sum.points??0)>=x.milestone))await db.houseUnlock.upsert({where:{houseId_milestone:{houseId:row.houseId,milestone:item.milestone}},create:{houseId:row.houseId,...item,unlockedAt:new Date()},update:{}});
 const [awards,unlocks]=await Promise.all([
  db.recognitionAward.findMany({orderBy:{awardedAt:"desc"},take:100,include:{student:{include:{user:true,houseMembership:{include:{house:true}}}}}}),
  db.houseUnlock.findMany({orderBy:[{claimedAt:"asc"},{unlockedAt:"desc"}],include:{house:true}})
 ]);
 async function revoke(formData:FormData){"use server";const admin=await getCurrentSession();if(!admin||admin.user.role!=="ADMIN")redirect("/admin");const id=String(formData.get("awardId")||"");const award=await db.recognitionAward.findUnique({where:{id}});if(!award)redirect(go("Recognition not found.","error"));if(award.revokedAt)redirect(go("Recognition was already revoked.","error"));
  await db.$transaction(async tx=>{await tx.recognitionAward.update({where:{id},data:{isPublic:false,revokedAt:new Date(),revokedByUserId:admin.user.id}});
   const original=await tx.housePointLedger.findFirst({where:{studentId:award.studentId,sourceId:id,sourceType:"RECOGNITION_"+award.badgeKey}});
   const reversed=await tx.housePointLedger.findFirst({where:{studentId:award.studentId,sourceId:id,sourceType:"RECOGNITION_REVERSAL"}});
   if(original&&!reversed&&original.points>0)await tx.housePointLedger.create({data:{houseId:original.houseId,studentId:original.studentId,points:-original.points,reason:"Revoked: "+award.title,sourceType:"RECOGNITION_REVERSAL",sourceId:id}});
   if(award.beneficiaryStudentId){const other=await tx.housePointLedger.findFirst({where:{studentId:award.beneficiaryStudentId,sourceId:id,sourceType:{startsWith:"CROSS_HOUSE_"}}});const undone=await tx.housePointLedger.findFirst({where:{studentId:award.beneficiaryStudentId,sourceId:id,sourceType:"CROSS_HOUSE_REVERSAL"}});if(other&&!undone&&other.points>0)await tx.housePointLedger.create({data:{houseId:other.houseId,studentId:other.studentId,points:-other.points,reason:"Revoked cross-House award: "+award.title,sourceType:"CROSS_HOUSE_REVERSAL",sourceId:id}});}
  });revalidatePath("/admin/rewards");revalidatePath("/student/rewards");revalidatePath("/parent/rewards");revalidatePath("/certificates/"+award.certificateCode);redirect(go("Recognition revoked and awarded points safely reversed."));
 }
 async function claim(formData:FormData){"use server";const admin=await getCurrentSession();if(!admin||admin.user.role!=="ADMIN")redirect("/admin");await db.houseUnlock.update({where:{id:String(formData.get("unlockId")||"")},data:{claimedAt:new Date()}});revalidatePath("/admin/rewards");redirect(go("House reward marked as delivered."));}
 return <main className="min-h-screen bg-[#edf2f6] py-6"><div className="section-container space-y-5"><ActionToast message={params.notice} tone={params.tone}/>
  <header className="rounded-[26px] bg-[#172842] p-6 text-white"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#f4bd72]">Strict reward governance</p><h1 className="mt-2 text-2xl font-semibold">Recognition & House Rewards</h1><p className="mt-2 text-sm text-[#cfdaea]">Audit badges, reverse incorrect points safely, and record delivered rewards.</p></div><div className="flex gap-2"><Link href="/admin/community" className="rounded-full border border-white/25 px-4 py-2">Community</Link><Link href="/admin" className="rounded-full bg-white px-4 py-2 text-[#172842]">Admin home</Link></div></div></header>
  <section className="grid gap-4 sm:grid-cols-3">{[["Active",awards.filter(x=>!x.revokedAt).length],["Revoked",awards.filter(x=>x.revokedAt).length],["House unlocks",unlocks.length]].map(x=><div key={String(x[0])} className="rounded-[22px] border bg-white p-5"><p className="text-3xl font-semibold text-[#22304a]">{x[1]}</p><p className="text-sm text-[#617184]">{x[0]}</p></div>)}</section>
  <section className="rounded-[26px] border bg-white p-5"><h2 className="text-xl font-semibold text-[#22304a]">House unlock fulfilment</h2><p className="text-sm text-[#617184]">Mark delivered only after the promised reward has been given.</p><div className="mt-4 grid gap-3 lg:grid-cols-2">{unlocks.map(u=><div key={u.id} className="flex items-center justify-between gap-4 rounded-2xl bg-[#fbf6ef] p-4"><div><p className="font-semibold">{u.house.name}: {u.title}</p><p className="text-sm text-[#617184]">{u.milestone} points · {u.description}</p><p className="text-xs text-[#7a8797]">{u.claimedAt?"Delivered "+u.claimedAt.toLocaleDateString("en-GB"):"Awaiting delivery"}</p></div>{!u.claimedAt?<form action={claim}><input type="hidden" name="unlockId" value={u.id}/><button className="rounded-full bg-[#2f6b4b] px-4 py-2 text-sm font-semibold text-white">Mark delivered</button></form>:<span className="font-semibold text-[#2f6b4b]">Delivered</span>}</div>)}{!unlocks.length?<p className="text-sm text-[#617184]">No reward milestone unlocked yet.</p>:null}</div></section>
  <section className="rounded-[26px] border bg-white p-5"><h2 className="text-xl font-semibold text-[#22304a]">Recognition audit history</h2><p className="text-sm text-[#617184]">Revocation keeps the original record and adds reversal ledger entries.</p><div className="mt-4 space-y-3">{awards.map(a=><article key={a.id} className={"grid gap-4 rounded-2xl border p-4 lg:grid-cols-[1fr_auto] "+(a.revokedAt?"bg-[#fff5f5]":"bg-[#fffaf4]")}><div><p className="font-semibold text-[#22304a]">{a.title} · {name(a.student)} <span className={a.revokedAt?"text-[#b24646]":"text-[#2f6b4b]"}>{a.revokedAt?"REVOKED":"ACTIVE"}</span></p><p className="mt-2 text-sm text-[#617184]">{a.evidence||a.description}</p><p className="mt-2 text-xs text-[#7a8797]">{a.student.houseMembership?.qabilaGroup||a.student.houseMembership?.house.name||"No House"} · {a.pointsBonus} points · {a.awardedAt.toLocaleString("en-GB")}</p></div>{!a.revokedAt?<form action={revoke}><input type="hidden" name="awardId" value={a.id}/><button className="rounded-full border border-[#efb3b3] px-4 py-2 text-sm font-semibold text-[#b24646]">Revoke & reverse points</button></form>:null}</article>)}{!awards.length?<p>No recognitions yet.</p>:null}</div></section>
 </div></main>;
}