import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { Download, HeartHandshake, Trash2 } from "lucide-react";
import { ActionToast } from "@/components/dashboard/ActionToast";
import { TeacherDashboardFrame, TeacherMetricGrid, TeacherSection } from "@/components/dashboard/teacher/TeacherDashboardFrame";
import { TeacherRewardWorkspaceTabs } from "@/components/dashboard/teacher/TeacherRewardWorkspaceTabs";
import { getCurrentSession, getDashboardHome } from "@/lib/auth/session";
import { MUM_CHARACTER_BADGES, awardParentRecognition } from "@/lib/community/parent-recognition";
import { pointDayKey } from "@/lib/community/point-awards";
import { db } from "@/lib/db";
import { getTeacherDashboardData } from "@/lib/teacher/dashboard";
import { getTeacherNavItems } from "@/lib/teacher/nav";
type Props={searchParams?:Promise<{awarded?:string;removed?:string;error?:string;certificate?:string}>};
function weekKey(){const [y,m,d]=pointDayKey().split("-").map(Number);const date=new Date(Date.UTC(y,m-1,d));date.setUTCDate(date.getUTCDate()-((date.getUTCDay()+6)%7));return date.toISOString().slice(0,10)}
export default async function ParentRecognitionPage({searchParams}:Props){
 const session=await getCurrentSession();if(!session)redirect("/auth/login");if(session.user.role!=="TEACHER")redirect(getDashboardHome(session.user.role));
 const dashboard=await getTeacherDashboardData(session.user.id);if(!dashboard)redirect("/teacher-registration");const params=searchParams?await searchParams:{};
 const studentIds=[...new Set(dashboard.rosters.flatMap((roster)=>roster.students.map((student)=>student.id)))];
 const links=studentIds.length?await db.parentStudent.findMany({where:{studentId:{in:studentIds}},include:{parent:{include:{user:true}},student:{include:{user:true}}}}):[];
 const parents=[...new Map(links.map((link)=>[link.parent.id,{id:link.parent.id,name:`${link.parent.user.firstName} ${link.parent.user.lastName??""}`.trim()||link.parent.user.email,email:link.parent.user.email,children:[]}])).values()];
 for(const parent of parents) parent.children=[...new Set(links.filter((link)=>link.parentId===parent.id).map((link)=>link.student.displayName||link.student.user.firstName))] as never[];
 parents.sort((a,b)=>a.name.localeCompare(b.name));
 const recent=await db.parentRecognitionAward.findMany({where:{awardedByUserId:session.user.id,isPublic:true,revokedAt:null},orderBy:{awardedAt:"desc"},take:20,include:{parent:{include:{user:true}}}});
 async function award(formData:FormData){"use server";const current=await getCurrentSession();if(!current||current.user.role!=="TEACHER")redirect("/auth/login");const currentDashboard=await getTeacherDashboardData(current.user.id);if(!currentDashboard)redirect("/teacher-registration");const eligibleStudentIds=[...new Set(currentDashboard.rosters.flatMap((roster)=>roster.students.map((student)=>student.id)))];const eligibleParents=eligibleStudentIds.length?await db.parentStudent.findMany({where:{studentId:{in:eligibleStudentIds}},select:{parentId:true}}):[];const allowed=new Set(eligibleParents.map((item)=>item.parentId));const parentId=String(formData.get("parentId")||"");const badgeKey=String(formData.get("badgeKey")||"");const evidence=String(formData.get("evidence")||"").trim().slice(0,240);if(!allowed.has(parentId)||!MUM_CHARACTER_BADGES.some((badge)=>badge.key===badgeKey)||evidence.length<12)redirect("/teacher/parent-recognition?error=Choose%20an%20eligible%20mum,%20badge,%20and%20a%20clear%20reason.");const created=await awardParentRecognition({parentId,badgeKey,evidence,awardedByUserId:current.user.id,sourceId:`${current.user.id}:${badgeKey}:${weekKey()}`,featuredWeek:weekKey()});revalidatePath("/teacher/parent-recognition");revalidatePath("/parent");revalidatePath(`/parent-certificates/${created.certificateCode}`);redirect(`/teacher/parent-recognition?awarded=1&certificate=${created.certificateCode}`)}
 async function remove(formData:FormData){"use server";const current=await getCurrentSession();if(!current||current.user.role!=="TEACHER")redirect("/auth/login");const id=String(formData.get("awardId")||"");const item=await db.parentRecognitionAward.findFirst({where:{id,awardedByUserId:current.user.id,revokedAt:null}});if(!item)redirect("/teacher/parent-recognition?error=Award%20not%20found%20or%20not%20owned%20by%20you.");await db.$transaction([db.parentRecognitionAward.update({where:{id:item.id},data:{isPublic:false,revokedAt:new Date(),revokedByUserId:current.user.id}}),db.notification.deleteMany({where:{href:`/parent-certificates/${item.certificateCode}`}})]);revalidatePath("/teacher/parent-recognition");revalidatePath("/parent");revalidatePath(`/parent-certificates/${item.certificateCode}`);redirect("/teacher/parent-recognition?removed=1")}
 return <TeacherDashboardFrame title="Live Points & Recognition" subtitle="Celebrate an active mum whose Islamic character and support strengthen her family and our community." navItems={getTeacherNavItems()}><ActionToast message={params.awarded?"Mum recognition awarded, certificate created, and the parent notified by portal and email.":params.removed?"Test Mum certificate removed successfully.":params.error} tone={params.error?"error":"success"}/><TeacherRewardWorkspaceTabs active="parents"/><TeacherMetricGrid metrics={[{label:"Eligible mums",value:String(parents.length),hint:"Parents linked to your roster."},{label:"Islamic badges",value:String(MUM_CHARACTER_BADGES.length),hint:"Mum of the Week is selected by default."},{label:"Reason",value:"Required",hint:"Printed on the certificate."},{label:"Print / PDF",value:"Included",hint:"Teacher and parent can download."}]}/>
 <TeacherSection eyebrow="Parent recognition" title="Award Mum of the Week"><div className="mb-5 flex gap-4 rounded-[24px] border border-[#e9c6b6] bg-gradient-to-r from-[#fff2ea] to-[#fffaf5] p-5"><span className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-[#703d55] text-[#ffd8b5]"><HeartHandshake className="h-7 w-7"/></span><div><p className="font-black text-[#38243a]">Honour the mums helping faith and learning flourish.</p><p className="mt-1 text-sm leading-6 text-[#6d5c69]">Select a roster-linked parent, choose an Islamic character badge, and record a concise observed reason.</p></div></div><form action={award} className="grid gap-4 lg:grid-cols-2"><label className="grid gap-2 text-sm font-bold text-[#22304a]">Mum<select name="parentId" required className="rounded-2xl border border-[#d8e3ed] bg-white px-4 py-3 font-normal"><option value="">Choose parent</option>{parents.map((parent)=><option key={parent.id} value={parent.id}>{parent.name}{parent.children.length?` — ${parent.children.join(", ")}`:""}</option>)}</select></label><label className="grid gap-2 text-sm font-bold text-[#22304a]">Islamic character badge<select name="badgeKey" required defaultValue="MUM_OF_WEEK" className="rounded-2xl border border-[#d8e3ed] bg-white px-4 py-3 font-normal">{MUM_CHARACTER_BADGES.map((badge)=><option key={badge.key} value={badge.key}>{badge.title}{badge.key==="MUM_OF_WEEK"?" — default":""}</option>)}</select></label><label className="grid gap-2 text-sm font-bold text-[#22304a] lg:col-span-2">Short reason shown on dashboard and certificate<textarea name="evidence" required minLength={12} maxLength={240} rows={4} className="rounded-2xl border border-[#d8e3ed] px-4 py-3 font-normal" placeholder="Example: For consistently encouraging Islamic learning, supporting attendance, and helping other families with kindness."/><span className="text-xs font-normal text-[#7a8797]">Maximum 240 characters.</span></label><button className="w-fit rounded-full bg-[#703d55] px-6 py-3 text-sm font-bold text-white">Award Mum badge & certificate</button></form>{params.certificate?<a href={`/parent-certificates/${params.certificate}`} className="mt-5 inline-flex items-center gap-2 rounded-full border border-[#c68e76] px-5 py-3 text-sm font-bold text-[#703d55]"><Download className="h-4 w-4"/>Open, print or save certificate</a>:null}</TeacherSection>
 <TeacherSection eyebrow="Teacher award history" title="My recent Mum certificates"><div className="grid gap-3">{recent.map((item)=><article key={item.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-[#ead9df] bg-[#fff9fb] p-4"><div><p className="font-black text-[#38243a]">{item.title} · {item.parent.user.firstName} {item.parent.user.lastName}</p><p className="mt-1 text-sm text-[#6d5c69]">{item.evidence}</p><p className="mt-1 text-xs text-[#91828b]">{item.awardedAt.toLocaleDateString("en-GB")}</p></div><div className="flex gap-2"><a href={`/parent-certificates/${item.certificateCode}`} className="rounded-full border px-4 py-2 text-xs font-bold">Open / download</a><details className="relative"><summary className="cursor-pointer list-none rounded-full border border-[#efb3b3] px-4 py-2 text-xs font-bold text-[#b24646]">Remove</summary><form action={remove} className="absolute right-0 z-20 mt-2 w-64 rounded-2xl border bg-white p-4 shadow-xl"><input type="hidden" name="awardId" value={item.id}/><p className="text-xs">Remove this test certificate?</p><button className="mt-3 inline-flex items-center gap-2 rounded-full bg-[#b24646] px-4 py-2 text-xs font-bold text-white"><Trash2 className="h-3.5 w-3.5"/>Yes, remove</button></form></details></div></article>)}{!recent.length?<p className="rounded-2xl bg-[#f8fafc] p-5 text-sm text-[#617184]">No Mum certificates assigned yet.</p>:null}</div></TeacherSection></TeacherDashboardFrame>
}