import Link from "next/link";
import { minutesLabel, monthLabel, pounds, type PayrollSnapshot } from "@/lib/payroll/calculation";
export function PayslipCard({snapshot,id,preview=false}:{snapshot:PayrollSnapshot;id?:string;preview?:boolean}) {
 const t=snapshot.totals;
 return <section className="overflow-hidden rounded-3xl border border-[#eadfce] bg-white shadow-sm">
  <div className="flex flex-wrap items-start justify-between gap-5 bg-[#22304a] p-6 text-white"><div><p className="text-xs font-semibold uppercase tracking-widest text-[#ffce83]">{preview?"Payslip preview":"Paid payslip"}</p><h2 className="mt-2 text-2xl font-semibold">{monthLabel(snapshot.month)} payslip</h2><p className="mt-1 text-sm text-slate-200">{snapshot.teacherName}</p></div><div className="text-right"><p className="text-xs text-slate-200">{preview?"Final payment":"Amount paid"}</p><p className="mt-1 text-3xl font-bold text-[#ffce83]">{pounds(t.totalPence)}</p>{snapshot.showPkr && t.pkr!==null && <p className="mt-1 text-sm">(PKR {t.pkr.toLocaleString("en-GB")} equivalent)</p>}</div></div>
  <div className="space-y-5 p-6"><div className="grid gap-3 sm:grid-cols-3">{[["Sessions",t.sessions],["Paid hours",t.paidHours],["Actual teaching time",minutesLabel(t.actualMinutes)]].map(([label,value])=><div key={label} className="rounded-2xl bg-[#f7f4eb] p-4"><p className="text-xs text-[#617184]">{label}</p><p className="mt-1 text-xl font-semibold text-[#22304a]">{value}</p></div>)}</div>
  <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs text-[#617184]"><tr>{["Programme","Sessions","Paid hours","Rate / hour","Amount"].map(h=><th key={h} className="px-2 py-3">{h}</th>)}</tr></thead><tbody>{snapshot.lines.map((line,i)=><tr key={i} className="border-t border-[#eadfce]"><td className="px-2 py-3 font-medium">{line.label}</td><td className="px-2 py-3">{line.sessions}</td><td className="px-2 py-3">{line.paidHours}</td><td className="px-2 py-3">GBP {line.hourlyRate}</td><td className="px-2 py-3 font-semibold">{pounds(t.linePence[i])}</td></tr>)}</tbody></table></div>
  <p className="text-xs text-[#617184]">Paid hours x hourly rate, with final amounts rounded to the nearest penny. Actual teaching time is shown separately for reference.</p>
  {t.adjustmentPence!==0 && <p className="rounded-xl bg-amber-50 p-3 text-sm">Adjustment: {pounds(t.adjustmentPence)} - {snapshot.adjustmentReason}</p>}
  <div className="flex flex-wrap justify-between gap-3 rounded-2xl bg-emerald-50 p-4 text-emerald-900"><span className="font-semibold">{preview?"Final payment":"Paid"}{snapshot.paidOn?" - "+snapshot.paidOn:""}</span><strong>{pounds(t.totalPence)}</strong></div>
  {snapshot.paymentReference && <p className="text-sm">Payment reference: {snapshot.paymentReference}</p>}{snapshot.note && <p className="whitespace-pre-wrap rounded-xl bg-[#f7f4eb] p-4 text-sm">{snapshot.note}</p>}
  {snapshot.showPkr && <p className="text-xs text-[#617184]">Conversion: GBP 1 = PKR {snapshot.fxRate} ({snapshot.fxDate}).</p>}
  <div className="flex flex-wrap gap-3"><Link href={(preview?"/admin/hours-log?month=":"/teacher/hours-log?month=")+snapshot.month} className="rounded-full bg-[#22304a] px-5 py-2 text-sm font-semibold text-white">Review all hours</Link>{id && snapshot.proof && <><a href={"/api/payroll/"+id+"/proof"+(preview?"?draft=1":"")} target="_blank" rel="noreferrer" className="rounded-full border px-5 py-2 text-sm">View payment screenshot</a><a href={"/api/payroll/"+id+"/proof?download=1"+(preview?"&draft=1":"")} className="rounded-full border px-5 py-2 text-sm">Download receipt</a></>}</div>
  </div></section>;
}
