import assert from 'node:assert/strict';
import test from 'node:test';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
function load(file,deps={}) {const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(new URL('../src/'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:id=>deps[id],Date,Intl,console,File,Buffer,FormData,URL});return exports;}
const calc=load('lib/payroll/calculation.ts');
const defaults=load('lib/payroll/september-defaults.ts');
test('September payroll matches all six source totals exactly',()=>{const gbp=[12855,6891,7422,14843,1325,4241],pkr=[48222,25851,27839,55679,4971,15908];defaults.SEPTEMBER_TEMPLATES.forEach((t,i)=>{const result=calc.calculatePayroll(defaults.emptyPayroll(t.lines,true));assert.equal(result.totalPence,gbp[i],t.name);assert.equal(result.pkr,pkr[i],t.name);});});
test('actual minutes do not change paid hours or payment',()=>{const input=defaults.emptyPayroll(defaults.SEPTEMBER_TEMPLATES[5].lines,true);const first=calc.calculatePayroll(input);const changed=calc.calculatePayroll({...input,lines:input.lines.map(l=>({...l,actualMinutes:300}))});assert.equal(first.totalPence,changed.totalPence);assert.equal(changed.paidHours,8);assert.equal(changed.actualMinutes,300);});
test('multiple programme rates and signed adjustments use exact arithmetic',()=>{const input=defaults.emptyPayroll(defaults.SEPTEMBER_TEMPLATES[0].lines,true);const result=calc.calculatePayroll({...input,adjustment:'-0.55'});assert.equal(result.totalPence,12800);assert.equal(result.sessions,22);assert.equal(result.actualMinutes,1971);});
test('invalid values, excessive decimals and negative totals cannot be saved',()=>{const input=defaults.emptyPayroll(defaults.SEPTEMBER_TEMPLATES[0].lines,true);for(const field of ['hourlyRate','paidHours'])for(const invalid of ['NaN','-1','Infinity','1e2','0.123456789'])assert.throws(()=>calc.calculatePayroll({...input,lines:[{...input.lines[0],[field]:invalid}]}));assert.throws(()=>calc.calculatePayroll({...input,adjustment:'-99999'}));assert.throws(()=>calc.calculatePayroll({...input,fxRate:'0'}));});
function harness({role='ADMIN',finance=true}={}) {
 let row=null;const revisions=[];const db={teacherProfile:{findUnique:async()=>({id:'teacher',user:{firstName:'Javeria',lastName:'Khuram'},payrollSettings:null})},teacherPayslip:{findUnique:async()=>row,create:async({data})=>row={id:'slip',...data},update:async({data})=>row={...row,...data},findMany:async({where})=>{assert.equal(where.teacher.userId,'teacher-user');assert.equal(where.publishedAt.not,null);return row?.publishedAt?[row]:[];}},teacherPayrollSettings:{upsert:async()=>{}},teacherPayslipRevision:{create:async({data})=>revisions.push(data)},$queryRaw:async()=>{}};db.$transaction=async fn=>fn(db);
 const service=load('lib/payroll/service.ts',{'server-only':{},'@prisma/client':{Prisma:{sql:()=>({})}},'@/lib/db':{db},'@/lib/auth/session':{getCurrentSession:async()=>({user:{id:'admin',role}})},'@/lib/admin/access':{canAccessAdminFinance:async()=>finance},'./calculation':calc,'./drive':{}});
 const input={...defaults.emptyPayroll(defaults.SEPTEMBER_TEMPLATES[5].lines,true),paidOn:'2026-09-30'};
 const form=(mode='save',version=0,payload=input)=>{const f=new FormData();for(const [k,v]of Object.entries({teacherId:'teacher',month:'2026-09',mode,version:String(version),payload:JSON.stringify(payload),paidConfirmed:'yes'}))f.set(k,v);return f;};return {service,form,revisions,input,get row(){return row;}};
}
test('non-finance admins and teachers cannot save payroll',async()=>{for(const options of [{role:'TEACHER'},{finance:false}]){const h=harness(options);await assert.rejects(h.service.savePayroll(h.form()),/access required/);assert.equal(h.row,null);}});
test('drafts stay private; publishing creates a frozen revision; later edits stay private',async()=>{const h=harness();await h.service.savePayroll(h.form());assert.equal(h.row.publishedData,undefined);assert.equal((await h.service.publishedPayslips('teacher-user')).length,0);await h.service.savePayroll(h.form('publish',1));assert.equal(h.revisions.length,1);assert.equal(h.row.publishedData.totals.totalPence,4241);await h.service.savePayroll(h.form('save',2,{...h.input,note:'Unpublished edit'}));assert.equal(h.row.publishedData.note,'');assert.equal(h.row.draftData.note,'Unpublished edit');assert.equal(h.revisions.length,1);});
test('stale retries do not duplicate publication',async()=>{const h=harness();await h.service.savePayroll(h.form('publish'));await assert.rejects(h.service.savePayroll(h.form('publish')),/another window/);assert.equal(h.revisions.length,1);});
test('publication requires actual payment confirmation and valid date',async()=>{const h=harness();const f=h.form('publish');f.set('paidConfirmed','no');await assert.rejects(h.service.savePayroll(f),/Confirm/);assert.throws(()=>h.service.validatePayroll({...h.input,paidOn:''},true));assert.throws(()=>h.service.validatePayroll({...h.input,paidOn:'2026-02-30'},true));assert.throws(()=>h.service.validatePayroll({...h.input,adjustment:'1',adjustmentReason:''},true));});
test('client supplied totals and receipt identifiers are ignored',async()=>{const h=harness();await h.service.savePayroll(h.form('publish',0,{...h.input,totals:{totalPence:1},proof:{fileId:'other-teacher'}}));assert.equal(h.row.publishedData.totals.totalPence,4241);assert.equal(h.row.publishedData.proof,null);});

test('Sabah account matches the Sister Saba reference without matching unrelated teachers',()=>{assert.equal(defaults.septemberTemplate({firstName:'Sabah',lastName:'Abdissamee',email:'teacher@example.test'}).key,'saba');assert.equal(defaults.septemberTemplate({firstName:'Dr. Jaweria',lastName:'Riaz',email:'other@example.test'}),undefined);});
function proofHarness({user={id:'owner',role:'TEACHER'},finance=false}={}) {
 let downloaded=null;const published={proof:{fileId:'published-receipt',name:'payment.png',mimeType:'image/png'}},draft={proof:{fileId:'draft-receipt',name:'draft.png',mimeType:'image/png'}};
 const api=load('app/api/payroll/[id]/proof/route.ts',{'next/server':{NextResponse:Response},'@/lib/auth/session':{getCurrentSession:async()=>user?{user}:null},'@/lib/admin/access':{canAccessAdminFinance:async()=>finance},'@/lib/db':{db:{teacherPayslip:{findFirst:async({where})=>!where.teacher||where.teacher.userId==='owner'?{publishedData:published,draftData:draft}:null}}},'@/lib/google-drive/client':{driveDownloadResponse:async id=>{downloaded=id;return new Response('image');}}});
 return {run:query=>api.GET({nextUrl:new URL('https://genmumin.com/api/payroll/slip/proof'+(query||''))},{params:Promise.resolve({id:'slip'})}),get downloaded(){return downloaded;}};
}
test('teachers cannot download another teacher receipt or draft evidence',async()=>{const other=proofHarness({user:{id:'other',role:'TEACHER'}});assert.equal((await other.run()).status,404);assert.equal(other.downloaded,null);const owner=proofHarness();assert.equal((await owner.run('?draft=1')).status,200);assert.equal(owner.downloaded,'published-receipt');});
test('only finance admins can view draft receipts; download is private',async()=>{const admin=proofHarness({user:{id:'admin',role:'ADMIN'},finance:true});const response=await admin.run('?draft=1&download=1');assert.equal(admin.downloaded,'draft-receipt');assert.match(response.headers.get('content-disposition'),/^attachment/);assert.equal(response.headers.get('cache-control'),'private, no-store');const denied=proofHarness({user:{id:'admin',role:'ADMIN'}});assert.equal((await denied.run()).status,404);});
test('signed-out receipt access is denied',async()=>{const h=proofHarness({user:null});assert.equal((await h.run()).status,401);assert.equal(h.downloaded,null);});
